### ISSUE TITLE
GCM  Initialization vector length

### ISSUE THREAD

**Issue by umayaval** [microsoftarchive/clrsecurity#1]
I have 16 bytes IV and then last 4 bytes is dynamic . Why  IV bytes length has to  be 12 bytes alone. If I give more than 12 byte, encryption is failing. Can it be made as configurable.?

**Comment by gonzalo-lorieto** [comment]
As far as I know, 12 byte is the maximum bytes allowed for IV

**Comment by bartonjs** [comment]
This project is just sharing the code from an old prototype library, there's no active maintenance.

In this case, the GCM Nonce length is a limit from Windows.  Windows crypto only supports 96-bit nonces.
