### ISSUE TITLE
BlockSize is incorrectly set to 16

### ISSUE THREAD

**Issue by Stevie-O** [microsoftarchive/clrsecurity#3]
The BlockSize and LegalBlockSizes properties are incorrectly set to 16, which causes errors when the data to be enciphered is not an exact multiple of 16 bytes.

This occurs because the BCryptAuthenticatedSymmetricAlgorithm constructor interrogates the "BlockLength" property, which is incorrect; [MSDN](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-property-identifiers) clearly states that this property only applies to block cipher modes, but AES-GCM is a stream-cipher mode.

**Comment by bartonjs** [comment]
This project is just sharing the code from an old prototype library, there's no active maintenance.

**Comment by bartonjs** [comment]
(All functionality from this library should be available in current versions of .NET Core.  If you think something's missing, please open an issue at https://github.com/dotnet/runtime/)
