### ISSUE TITLE
Unable to decrypt RSA/ECB/OAEPWithSHA-256AndMGF1Padding from Java to .NET

### ISSUE THREAD

**Issue by praveenk988** [microsoftarchive/clrsecurity#4]
We have a requirement where in Java does the encryption and .NET does the decryption. The issue is with Asymmetric decryption in .NET, the algorithm, mode and padding used in Java while encryption is "RSA/ECB/OAEPWithSHA-256AndMGF1Padding". On .NET, I have tried to decrypt in all different ways RsaCng, Rsa, Chilkat Rsa, Bouncy Castle with OAEP padding, nothing worked so far. Below are the code snippets. Only when Java's encryption approach is changed to "RSA/ECB/OAEPWithSHA-1AndMGF1Padding", .NET was able to decrypt, but due to security reasons, Java can't change the approach of encryption. We are using PEM file to decrypt, while using a CERT to encrypt. Please let us know the best way to fix the issue. Is it something to do with creating a PEM file which is SHA256 hash based? I would appreciate if someone can help me out.

Errors are mentioned below. RsaCng and Rsa:- Parameter is Incorrect

Java Snippet for Asymmetric Encryption:-

                 // Encrypt the symetric key
                 X509Certificate cert = ConduentCertificateLocator.getConduentCertificate();
                 PublicKey certKey = cert.getPublicKey();
                 Cipher c2 = Cipher.getInstance("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
                 //Cipher c2 = Cipher.getInstance("RSA");
                 c2.init(Cipher.ENCRYPT_MODE, certKey);
                 byte[] inputCertKey = key.getEncoded();
                 byte[] encryptedKey = c2.doFinal(inputCertKey);
                 String encryptedKeyUrl = encodeToURL(encryptedKey);

NET Snippet for Asymmetric Decryption:- We did try in few different ways. Below is the code.

a. RSACryptoService

           using (RSACryptoServiceProvider csp = new RSACryptoServiceProvider())
            {
                using (var stream = File.OpenRead(_appSettings.PEM))
                using (var reader = new PemUtils.PemReader(stream))
                {
                    var rsaParameters = reader.ReadRsaKey();
                    csp.ImportParameters(rsaParameters);

                    var resultBytes = csp.Decrypt(ksBytes, true);
                    finalResult = Convert.ToBase64String(resultBytes);
                }
            }
b. RsaCng

           using (RSA rsa = new RSACng())
            {
                using (var stream = File.OpenRead(_appSettings.PEM))
                using (var reader = new PemUtils.PemReader(stream))
                    rsa.ImportParameters(reader.ReadRsaKey());
                byte[] decrypted2 = rsa.Decrypt(ksBytes, RSAEncryptionPadding.OaepSHA256);
                var ss = Encoding.UTF8.GetString(decrypted2);
            }

**Comment by bartonjs** [comment]
This project is just sharing the code from an old prototype library, there's no active maintenance and your problem doesn't seem related.  A Q/A forum such as StackOverflow is likely a better fit.

For what it's worth, RSACryptoServiceProvider cannot do OAEP with a SHA-2 digest (such as SHA-256).  Your (b) sample looks correct, so debugging that is what I'd recommend.

**Comment by praveenk988** [comment]
> This project is just sharing the code from an old prototype library, there's no active maintenance and your problem doesn't seem related. A Q/A forum such as StackOverflow is likely a better fit.
> 
> For what it's worth, RSACryptoServiceProvider cannot do OAEP with a SHA-2 digest (such as SHA-256). Your (b) sample looks correct, so debugging that is what I'd recommend.

Thanks for the response. I'm so sorry that I have posted the issue over here. I will take it to Stackoverflow, but before I do that, one last help that I need from you is, currently I have a PEM file with a RSA Key value, whole MODULUS size is 256 bytes (2048 bits), in order for Java's encryption approach of "RSA/ECB/OAEPWithSHA-256AndMGF1Padding" to work in .NET, do I need to have a bigger sized RSA Key Value, I mean while creating PEM file do I need to specify SHA-2 digest?? or any PEM file generated usually works with SHA-2 digest? Please help me out. I'm lost and trying to decrypt from Java to .NET and there is no help in Internet on my usecase. my email id is praveenk988@gmail.com. 

I did follow your instruction of sample(b), our Java team changed MGF1 hash from default SHA-1 to SHA-256 with OAEP of SHA-256 hash, now I'm able to decrypt in .NET with RsaCng without any padding invalid errors but the result that I see is a bad string of characters, symbols and unicodes. 

I appreciate any help. Thank you.

**Comment by bartonjs** [comment]
> now I'm able to decrypt in .NET with RsaCng without any padding invalid errors but the result that I see is a bad string of characters, symbols and unicodes.

Sounds like the text -> bytes encoding in Java and the bytes -> text encoding in C# aren't the same.  Or it's binary data you encrypted, and not anything that turns into text well.
